version: 0.2

env:
  variables:
    AWS_DEFAULT_REGION: us-east-1

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - docker info
      - pip install --upgrade pip
      - pip install pytest moto boto3 requests aws-sam-cli

  build:
    commands:
      - sam --version
      - sam build

  post_build:
    commands:
      - pytest tests/unit

      - sam local start-api --port 3000 --env-vars env.json &
      - echo "Esperando a que la API esté arriba..."
      - sleep 5

      - pytest tests/integration

artifacts:
  files:
    - '**/*'
