version: 0.2

env:
  variables:
    AWS_DEFAULT_REGION: us-east-1
    # SAM_BUCKET: sam-deployments-youraccount-${STAGE}

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing Node.js dependencies...
      - cd src/register && npm install
      - cd ../..
      - cd src/login && npm install
      - cd ../..
      - echo Verifying Python installation...
      - python --version
      - echo Installing Python dependencies for SAM build...
      - pip install --upgrade pip
      - pip install -r requirements.txt

  pre_build:
    commands:
      - echo Running Node.js unit tests...
      - cd tests/unit && npm test
      - cd ../..

  build:
    commands:
      - echo Building with SAM...
      - sam build
      - echo Deploying with SAM...
      - sam package --resolve-s3 --output-template-file packaged.yaml

  post_build:
    commands:
      - echo Build and deploy complete.

artifacts:
  files:
    - packaged.yaml
  discard-paths: yes
