version = 0.1

[default.deploy.parameters]
stack_name = "tfm-unir"
resolve_s3 = true
s3_prefix = "tfm-unir"
region = "us-east-1"
capabilities = "CAPABILITY_IAM CAPABILITY_NAMED_IAM"
parameter_overrides = "BranchName=\"master\" Stage=\"dev\""
image_repositories = []
confirm_changeset = true
